name: recipe_widget
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: 1.1.0
  curved_labeled_navigation_bar: ^2.0.2
  cupertino_icons: ^1.0.2
  image_picker: ^1.0.4
  firebase_core: ^2.24.2
  firebase_auth: ^4.15.3
  cloud_firestore: ^4.13.6
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/background_image.png
    - assets/facebook_icon.png
    - assets/google_icon.png
    - assets/profile_pic.png
    - assets/meat.png
    - assets/sausage.png
    - assets/dough-rolling.png
    - assets/cheese.png
    - assets/lunch1.jpg
